### ISSUE TITLE
When asking the bot for a non-existent issue, it responds with the last queried issue

### ISSUE THREAD

**Issue by kleinesfilmroellchen** [SerenityOS/discord-bot#10]
When asking the bot to post the link to a non-existent issue via `!issue`, it will respond (given that the issue number format is technically correct) with the last existent issue you asked for. I tried this with the following conversation (https://discord.com/channels/830522505605283862/830721144674844703/836268667339669534):

```
# kleines Filmröllchen, Piano/DAW
!issue 6666
# Buggie
https://github.com/SerenityOS/serenity/issues/6666
# kleines Filmröllchen, Piano/DAW
!issue 6663
# Buggie
https://github.com/SerenityOS/serenity/issues/6666
# kleines Filmröllchen, Piano/DAW
!issue 6665
# Buggie
https://github.com/SerenityOS/serenity/issues/6665
```

This may only happen if the non-existent issue is a Pull Request instead.

**Comment by IdanHo** [comment]
the current issue/pr commands just do a fuzzy search for the pr/issue which matches the given keywords the most, so thats intended behaviour

**Comment by bgianfo** [comment]
#9 should fix this I think, as @mattco98 implemented a specialization for numeric issue lookup.

**Comment by kleinesfilmroellchen** [comment]
That seems good to me, closing.

**Comment by bgianfo** [comment]
Just to confirm the fix, I tested it just now: 

```
bgianf — Today at 10:43 AM
!issue 6663

Buggie - BOT — Today at 10:43 AM
No matching issues found :sadcaret:
```
