### ISSUE TITLE
test262 command fails when commit author has no GitHub account

### ISSUE THREAD

**Issue by sin-ack** [SerenityOS/discord-bot#379]
Example commit: https://github.com/serenityOS/serenity/commit/f55d7bf6f339af701d72204331fd0661a8bcd986
This is a patch from Anonymous, which doesn't have a GitHub account. Calling /test262 with this commit causes the bot to fail with: `Cannot read properties of null (reading 'login')`.

The bug is here: https://github.com/SerenityOS/discord-bot/blob/82aefca5388d195a9366fecb7536765a5b6f3f80/src/commands/test262Command.ts#L208

A null check needs to be added in case the commit author doesn't have a GitHub account.

**Comment by bgianfo** [comment]
@sin-ack do you want to send a PR since you figured out the issue?

**Comment by sin-ack** [comment]
Sure, I'll do it tomorrow.
