### ISSUE TITLE
Use lf endings

### ISSUE THREAD

**Issue by u9g** [SerenityOS/discord-bot#383]
When running prettier on the project, all files show as changed since they use crlf endings, so it would be better if all files just used lf, so this problem didn't exist

**Comment by linusg** [comment]
They don't use CRLF endings. Maybe your git is configured incorrectly and converted line endings automatically.

![image](https://user-images.githubusercontent.com/19366641/154816053-29106c9e-fc04-485a-bebb-028743696566.png)

(last two commands from https://stackoverflow.com/questions/73833/how-do-you-search-for-files-containing-dos-line-endings-crlf-with-grep-on-linu)
